### ISSUE TITLE
UnknownHostException crash

### ISSUE THREAD

**Issue by LasseMortensen** [cookie-information/android-release#28]
Hi,

We currently have this crash as our most occurring crash in our app. After some investigation it seems to be related to loading cookie-information.

**Cookie-information version:**
at least 1.0.6 to 1.0.14

**Device:**
59% Samsung
25% Oneplus
8% Huawei
4% Motorola
4% other

**OS:**
53% Android 13
17% Android 12
11% Android 10
9% Android 9
10% other

**Crashlog:**
```
Fatal Exception: java.net.UnknownHostException: Unable to resolve host "cdnapi-prod.azureedge.net": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
       at java.net.InetAddress.getAllByName(InetAddress.java:1154)
       at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Linux.android_getaddrinfo(Linux.java)
       at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
       at java.net.InetAddress.getAllByName(InetAddress.java:1154)
       at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

Unfortunately I do not have a reliable way to reproduce this crash. Let me know if you need any other information that I can provide

**Comment by HannahShulman** [comment]
@LasseMortensen Thank you for the information. I will investigate an update as soon as possible.

**Comment by HannahShulman** [comment]
Hello @LasseMortensen 
Based on my ability to reproduce, this issue has been fixed on version 2.0.2, please let me know if I can assist further with anything.
Thanks

**Comment by LasseMortensen** [comment]
@HannahShulman thanks,
I will verify and report back after out next release :)

**Comment by HannahShulman** [comment]
@LasseMortensen Please let me know if you still come across this issue, in the 2.0.7 release.
Thanks

**Comment by LasseMortensen** [comment]
@HannahShulman The crash still occurs in 2.0.7
